/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-04-01 09:57:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <title>eunisLogin</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/static/unis/themes/default/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/static/unis/themes/default/css/form.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/static/unis/themes/default/css/enisLogin.css\"/>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/static/plugin/jquery/jquery-1.8.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"box\">\r\n");
      out.write("    <h1 class=\"logo fl\"><!-- 左上的logo图片位置 webapp/static/unis/themes/default--> \r\n");
      out.write("        <a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/static/unis/themes/default/images/images/eunisLogo.png\" alt=\"\"/></a>\r\n");
      out.write("    </h1>\r\n");
      out.write("    <div class=\"rightHeart fr\">\r\n");
      out.write("        <em></em><a href=\"#\"><span>EUNIS用户登录注册页面</span></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"con\">\r\n");
      out.write("    <div class=\"box clear conBox posRel\">\r\n");
      out.write("        <a href=\"#\" class=\"fl conBg\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/static/unis/themes/default/images/images/bgUnis.png\" alt=\"\"/></a>\r\n");
      out.write("        <div class=\"login posRel\">\r\n");
      out.write("            <h5>用户登录</h5>\r\n");
      out.write("            <div id =\"div\"class=\"msg posAbso\">\r\n");
      out.write("                <em></em>\r\n");
      out.write("                <span id=\"sp\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"#\">\r\n");
      out.write("                <ul class=\"posRel\">\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"userName posRel\">\r\n");
      out.write("                        <em></em>\r\n");
      out.write("                        <input id=\"userName\" name=\"username\" value=\"10002092\"  onblur=\"checkUsername()\" onclick=\"rewrn()\" onfocus=\"rewrn()\" type=\"text\" placeholder=\"请输入账户名\"/>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"passwd posRel\">\r\n");
      out.write("                        <em></em>\r\n");
      out.write("                        <input id=\"passwd\" name=\"password\"  value=\"admin\" onblur=\"checkPasswd()\" onfocus=\"rewrp()\" type=\"password\"/>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"submitt\"><a href=\"#\" onclick=\"return checkfrom()\">登录</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"box\">\r\n");
      out.write("    <ul class=\"companyList clear\">\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">惠普</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">联想</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">戴尔</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">三星</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">H3C</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">紫光股份</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">启迪控股</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">清华控股</a></li>\r\n");
      out.write("        <li class=\"fl\"><a href=\"javascript:;\">清华大学</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <p>版权所有 © 2013 紫光数码（苏州）集团有限公司 All rights reserved. 京ICP备05015486号 京公网安备11010802015531号</p>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("//隐藏提示 \r\n");
      out.write("document.getElementById(\"div\").style.display=\"none\";\r\n");
      out.write("\t//用户id检查 现有 非空  ajax查是否存在\r\n");
      out.write("\tfunction checkUsername(){\r\n");
      out.write("\t\tdocument.getElementById(\"div\").style.display=\"none\";\r\n");
      out.write("\t    var username=$('#userName').val();\r\n");
      out.write("\t    if(!$.trim(username)){\r\n");
      out.write("\t    \t$(\"#sp\").html(\"用户账号不能为空\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"div\").style.display=\"\"\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t   \t}else{\r\n");
      out.write("\t   \t\tvar ok=\"ok\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype : 'POST', // http请求方式\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/exist\", // 服务器段url地址\r\n");
      out.write("\t\t\t\t\tasync : true, \r\n");
      out.write("\t\t\t\t\tdata : \"userid=\" + username, // 发送给服务器段的数据\r\n");
      out.write("\t\t\t\t\tdataType : 'json', // 告诉JQuery返回的数据格式\r\n");
      out.write("\t\t\t\t\tsuccess : function(data, msg) {\r\n");
      out.write("\t\t\t\t\t\tif (data.status != true) {//status 为false账号不存在\r\n");
      out.write("\t\t\t\t\t\t\tok=\"no\";\r\n");
      out.write("\t\t\t\t\t\t\t//显示提示\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"div\").style.display=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#sp\").html(data.message);\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tok=\"ok\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t//定义交互完成，并且服务器正确返回数据时调用的回调函数\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t if(ok==\"ok\"){\r\n");
      out.write("\t\t\t\t return true;\r\n");
      out.write("\t\t\t } else{\r\n");
      out.write("\t\t\t\t return false;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\t//密码检查 暂时有非空与长度检查，待加\r\n");
      out.write("\tfunction checkPasswd(){\r\n");
      out.write("\t    var passwd=$('#passwd').val();\r\n");
      out.write("\t    passwd1=passwd;\r\n");
      out.write("\t    if(!$.trim(passwd)){\r\n");
      out.write("\t    \t//显示提示框\r\n");
      out.write("\t    \tdocument.getElementById(\"div\").style.display=\"\";\r\n");
      out.write("\t    \t$(\"#sp\").html(\"用户密码不能为空\");\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t   \t}else if(passwd.length<5){\r\n");
      out.write("\t   \t\tdocument.getElementById(\"div\").style.display=\"\";\r\n");
      out.write("\t   \t\t$(\"#sp\").html(\"用户密码不少于5位\");\r\n");
      out.write("\t   \t\treturn false;\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//获取焦点时，回填输入的账号 隐藏上方提示\r\n");
      out.write("\tfunction rewrn(){\r\n");
      out.write("\t\tdocument.getElementById(\"div\").style.display=\"none\";\r\n");
      out.write("\t\t$(\"#sp\").html(\"\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//获取焦点时， 隐藏上方提示\r\n");
      out.write("\tfunction rewrp(){\r\n");
      out.write("\t\tdocument.getElementById(\"div\").style.display=\"none\";\r\n");
      out.write("\t\t$(\"#sp\").html(\"\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//按键回车  登录 \r\n");
      out.write("\tdocument.onkeydown = function(event) {\r\n");
      out.write("\t\te = event ? event : (window.event ? window.event : null);\r\n");
      out.write("\t\tif (e.keyCode == 13) {\r\n");
      out.write("\t\t\t//回车检测到了调用登录 ;\r\n");
      out.write("\t\t\tcheckfrom();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//登录前检查 \r\n");
      out.write("\tfunction checkfrom(){\r\n");
      out.write("\t\t//检查用户和密码\r\n");
      out.write("\t\tif(checkUsername()&&checkPasswd()){\r\n");
      out.write("\t\t\t//调用登录\r\n");
      out.write("\t\t\tlogin();\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"用户id和密码验证没通过\");\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//登录\r\n");
      out.write("\tfunction login() {\r\n");
      out.write("\t\t//获取用户账号\r\n");
      out.write("\t\tvar username = $('#userName').val();\r\n");
      out.write("\t\t//获取密码\r\n");
      out.write("\t\tvar password = $('#passwd').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'POST', // http请求方式\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/logincheck\", // 服务器段url地址\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdata : \"userid=\" + username+\"&passwd=\"+password, // 发送给服务器段的数据\r\n");
      out.write("\t\t\tdataType : 'json', //告诉JQuery返回的数据格式\r\n");
      out.write("\t\t\tsuccess : function(data, msg) {\r\n");
      out.write("\t\t\t\tif (data.status == true) {\r\n");
      out.write("\t\t\t\t\tif(data.message==\"\"||data.message==\"null\"||data.message==undefined){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/main-easyui.jsp\";\r\n");
      out.write("\t\t\t\t\t\t//window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jsp/easyui.jsp\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+data.message;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"div\").style.display=\"\";\r\n");
      out.write("\t\t\t\t\t$(\"#sp\").html(data.message);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(msg) {\r\n");
      out.write("\t\t\t\talert(\"登录失败\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//定义交互完成，并且服务器正确返回数据时调用的回调函数\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
